[tool.poetry]
name = "samolet-ml"
version = "0.0.1"
description = "ML сервис для решения задачи о вычислении степени отделки квартиры"
authors = ["Aleksandr Lobanov <aleksandr.lobanov.official@gmail.com>"]
readme = "README.md"
packages = []

[tool.poetry.dependencies]
python = ">=3.10"
opencv-python = "^4.7.0.72"
rich = "^13.3.5"
pytest = "^7.3.1"
ultralytics = "^8.0.107"
urllib3 = "^1.26.0"
fastapi = "^0.95.2"
python-multipart = "^0.0.6"
uvicorn = "^0.22.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
